(()=>{
  "use strict";
  const catalog=(window.LISHI_DATA&&Array.isArray(window.LISHI_DATA.cars))?window.LISHI_DATA.cars:[];
  const profileCatalog=(window.LISHI_PROFILES&&window.LISHI_PROFILES.profiles)||{};
  const profileSources=(window.LISHI_PROFILES&&window.LISHI_PROFILES.sources)||{};
  const keyPhotoReference=(window.LISHI_PROFILES&&window.LISHI_PROFILES.keyPhotoReference)||null;
  const $=id=>document.getElementById(id);
  const elements={query:$("q"),brand:$("brand"),brandPicker:$("brandPicker"),brandButton:$("brandButton"),brandButtonIcon:$("brandButtonIcon"),brandButtonText:$("brandButtonText"),brandMenu:$("brandMenu"),market:$("market"),ignition:$("ignition"),year:$("year"),tool:$("tool"),results:$("results"),stats:$("stats"),chips:$("brandChips"),modeHelp:$("modeHelp"),showAll:$("showAll"),catalogPill:$("catalogPill"),clear:$("clr"),reset:$("resetApp"),updateStatus:$("updateStatus"),photoDialog:$("photoDialog"),photoTitle:$("photoTitle"),photoClose:$("photoClose"),photoLoading:$("photoLoading"),photoImage:$("photoImage"),photoMessage:$("photoMessage"),photoCredit:$("photoCredit"),photoCreditText:$("photoCreditText"),photoSource:$("photoSource"),manageSources:$("manageSources"),sourceCount:$("sourceCount"),sourcesDialog:$("sourcesDialog"),sourcesClose:$("sourcesClose"),sourceFile:$("sourceFile"),clearSources:$("clearSources"),exportData:$("exportData"),importStatus:$("importStatus"),builtinCatalogSummary:$("builtinCatalogSummary"),importedSourceSummary:$("importedSourceSummary"),importedSourceState:$("importedSourceState")};
  const STORAGE_KEYS={external:"lishi-finder-external-v1",notes:"lishi-finder-notes-v1"};
  const state={mode:"auto",showAll:false,photoRequest:0,externalRecords:[],notes:{}};
  const photoCache=new Map();let photoController=null;
  const brandIcons={
    Audi:'<svg viewBox="0 0 48 48" focusable="false"><g fill="none" stroke="currentColor" stroke-width="3.2"><circle cx="9" cy="24" r="7.5"/><circle cx="19" cy="24" r="7.5"/><circle cx="29" cy="24" r="7.5"/><circle cx="39" cy="24" r="7.5"/></g></svg>',
    BMW:'<svg viewBox="0 0 48 48" focusable="false"><circle cx="24" cy="24" r="20" fill="#111827"/><circle cx="24" cy="24" r="15" fill="#fff"/><path d="M24 24V9a15 15 0 0 1 15 15Z" fill="#1d8bd1"/><path d="M24 24v15A15 15 0 0 1 9 24Z" fill="#1d8bd1"/><circle cx="24" cy="24" r="15" fill="none" stroke="#111827" stroke-width="2"/></svg>',
    Citroen:'<svg viewBox="0 0 48 48" focusable="false"><g fill="none" stroke="#d71920" stroke-width="5" stroke-linecap="round" stroke-linejoin="round"><path d="m10 25 14-10 14 10"/><path d="m10 36 14-10 14 10"/></g></svg>',
    Dacia:'<svg viewBox="0 0 48 48" focusable="false"><path d="M7 11h34v14c0 9-7 15-17 18C14 40 7 34 7 25Z" fill="#0f6fae"/><path d="M16 18h9c7 0 11 3 11 8s-4 8-11 8h-9Zm7 5v6h3c3 0 4-1 4-3s-1-3-4-3Z" fill="#fff"/></svg>',
    'Mercedes-Benz':'<svg viewBox="0 0 48 48" focusable="false"><circle cx="24" cy="24" r="19" fill="none" stroke="currentColor" stroke-width="2.6"/><path d="M24 7 28 27 24 24 20 27Zm4 20 12 9-16-12Zm-8 0L8 36l16-12Z" fill="currentColor"/></svg>',
    Renault:'<svg viewBox="0 0 48 48" focusable="false"><path d="M24 4 41 24 24 44 7 24Zm0 8L14 24l10 12 10-12Z" fill="#f4c300" stroke="#212121" stroke-width="2" fill-rule="evenodd"/></svg>',
    Toyota:'<svg viewBox="0 0 48 48" focusable="false"><g fill="none" stroke="#d71920" stroke-width="2.8"><ellipse cx="24" cy="24" rx="20" ry="13"/><ellipse cx="24" cy="24" rx="8" ry="13"/><ellipse cx="24" cy="18" rx="15" ry="6"/></g></svg>',
    Volkswagen:'<svg viewBox="0 0 48 48" focusable="false"><circle cx="24" cy="24" r="20" fill="#0b5a9c"/><circle cx="24" cy="24" r="16" fill="none" stroke="#fff" stroke-width="2"/><path d="m14 13 7 17 3-8 3 8 7-17M12 25l8 12 4-10 4 10 8-12" fill="none" stroke="#fff" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/></svg>'
  };
  const marketNames={AU:"Австралія",US:"США",EU:"Європа",ME:"Близький Схід",KR:"Південна Корея",BR:"Бразилія",CAN:"Канада",JP:"Японія",ASIA:"Азія",GLOBAL:"Глобальний",UNSPECIFIED:"Не вказано"};
  const ignitionNames={key:"Механічний ключ",smart:"Смарт-ключ / слот",prox:"Безключовий доступ",unknown:"Не вказано"};
  const keyShapeNames={edge:"Нарізний профіль",laser:"Внутрішній / лазерний профіль",tibbe:"Профіль Tibbe",fob:"Смарт-ключ із аварійним лезом",unknown:"Форма ще не підтверджена"};
  const verificationNames={user:"Підтверджено вашими скріншотами",official:"Підтверджено офіційним джерелом",reference:"Довідникова форма — звірити",unknown:"Потребує перевірки"};
  const normalize=value=>String(value||"").toLocaleLowerCase("uk").trim();
  const uniqueSorted=items=>[...new Set(items.filter(Boolean))].sort((a,b)=>a.localeCompare(b,"uk"));
  const isVerified=record=>record.status==="verified"&&Boolean(record.lishi);
  const sourceRank=record=>record.source==="Скріншот користувача"?0:1;
  const sortRecords=(left,right)=>sourceRank(left)-sourceRank(right)||(left.brand+" "+left.model+" "+left.years).localeCompare(right.brand+" "+right.model+" "+right.years,"uk");
  const sourceLinks=[{name:"Original Lishi",url:"https://www.originallishi.com/lishi-tools-full-list/"},{name:"Genuine Lishi",url:"https://www.genuinelishi.com/"},{name:"AKS Reference Guide",url:"https://fliphtml5.com/aswuk/juqd/American_Key_Supply_-_Lishi_Reference_Guide_2024/"}];
  function readStoredJson(key,fallback){try{const value=localStorage.getItem(key);return value?JSON.parse(value):fallback;}catch(error){return fallback;}}
  function storeJson(key,value){try{localStorage.setItem(key,JSON.stringify(value));return true;}catch(error){return false;}}
  function recordKey(record){return [record.brand,record.model,record.years,(record.markets||[]).join(","),record.ignition,record.lishi].map(normalize).join("|");}
  function baseModel(value){return normalize(value).replace(/\([^)]*\)/g," ").replace(/\b(key|start|prox|proximity|smart|slot|remote)\b/g," ").replace(/[^\p{L}\p{N}]+/gu," ").replace(/\s+/g," ").trim();}
  function yearsOverlap(left,right){const leftFrom=Number(left.yearFrom)||0,leftTo=Number(left.yearTo)||9999,rightFrom=Number(right.yearFrom)||0,rightTo=Number(right.yearTo)||9999;if(!leftFrom||!rightFrom)return true;return leftFrom<=rightTo&&rightFrom<=leftTo;}
  function sameVehicle(left,right){if(normalize(left.brand)!==normalize(right.brand))return false;const leftModel=baseModel(left.model),rightModel=baseModel(right.model);if(!leftModel||!rightModel)return false;return (leftModel===rightModel||leftModel.includes(rightModel)||rightModel.includes(leftModel))&&yearsOverlap(left,right);}
  function safeSourceUrl(value){try{const url=new URL(String(value||""));return ["http:","https:"].includes(url.protocol)?url.href:"";}catch(error){return "";}}
  function safeImageUrl(value){const text=String(value||"").trim();if(!text)return"";try{const url=new URL(text,location.href);return ["http:","https:"].includes(url.protocol)?url.href:"";}catch(error){return"";}}
  function yearRange(raw){
    const text=String(raw.years||raw.year||raw.year_range||raw["роки"]||"").trim();const found=text.match(/(19|20)\d{2}/g)||[];const from=Number(raw.yearfrom||raw.yearFrom||raw.year_from||found[0])||null;const to=Number(raw.yearto||raw.yearTo||raw.year_to||found.at(-1))||from;
    return{years:text||(from?(from===to?String(from):from+"-"+to):""),yearFrom:from,yearTo:to};
  }
  function firstField(raw,names){for(const name of names){if(raw[name]!==undefined&&String(raw[name]).trim())return raw[name];}return "";}
  function normalizeImportedRecord(raw,defaultSource,index){
    const normalizedRaw={};Object.entries(raw||{}).forEach(([key,value])=>{normalizedRaw[normalize(key).replace(/\s+/g,"_")]=value;});
    const brand=String(firstField(normalizedRaw,["brand","make","марка","manufacturer"])).trim();const model=String(firstField(normalizedRaw,["model","vehicle","модель","автомобіль"])).trim();const lishi=String(firstField(normalizedRaw,["lishi","tool","reference","keyway","код","інструмент"])).trim().toUpperCase();if(!brand||!model||!lishi)return null;
    const range=yearRange(normalizedRaw);const marketValue=firstField(normalizedRaw,["market","markets","ринок"]);const markets=Array.isArray(marketValue)?marketValue.map(String):String(marketValue||"").split(/[;,|]/).map(value=>value.trim()).filter(Boolean);
    return{brand,model,years:range.years,yearFrom:range.yearFrom,yearTo:range.yearTo,markets,ignition:String(firstField(normalizedRaw,["ignition","key_type","тип_ключа"])||"unknown"),lishi,chip:String(firstField(normalizedRaw,["chip","transponder","чип"])||"").trim(),keyShape:String(firstField(normalizedRaw,["keyshape","key_shape","форма_ключа"])||"").trim().toLowerCase(),keyPhoto:safeImageUrl(firstField(normalizedRaw,["keyphoto","key_photo","фото_ключа"])),keyPhotoAlt:String(firstField(normalizedRaw,["keyphotoalt","key_photo_alt","опис_фото_ключа"])||"").trim(),keyPhotoSource:safeSourceUrl(firstField(normalizedRaw,["keyphotosource","key_photo_source","джерело_фото_ключа"])),status:"verified",source:String(firstField(normalizedRaw,["source","database","джерело"])||defaultSource||"Імпорт").trim(),sourceUrl:safeSourceUrl(firstField(normalizedRaw,["sourceurl","source_url","url","посилання"])),note:String(firstField(normalizedRaw,["note","notes","примітка"])||"").trim(),externalId:"external-"+Date.now()+"-"+index};
  }
  function parseCsv(text){
    const rows=[];let row=[],cell="",quoted=false;for(let index=0;index<text.length;index+=1){const char=text[index],next=text[index+1];if(char==='"'&&quoted&&next==='"'){cell+='"';index+=1;}else if(char==='"'){quoted=!quoted;}else if(char===","&&!quoted){row.push(cell);cell="";}else if((char==="\n"||char==="\r")&&!quoted){if(char==="\r"&&next==="\n")index+=1;row.push(cell);if(row.some(value=>String(value).trim()))rows.push(row);row=[];cell="";}else cell+=char;}row.push(cell);if(row.some(value=>String(value).trim()))rows.push(row);if(rows.length<2)return[];const headers=rows[0].map(value=>String(value).trim());return rows.slice(1).map(values=>Object.fromEntries(headers.map((header,index)=>[header,values[index]||""])));
  }
  function ukCount(count,one,few,many){const lastTwo=count%100,last=count%10;return count+" "+(lastTwo>=11&&lastTwo<=14?many:(last===1?one:(last>=2&&last<=4?few:many)));}
  function updateSourceSummary(){
    const count=state.externalRecords.length;const sources=uniqueSorted(state.externalRecords.map(record=>record.source));elements.sourceCount.textContent=ukCount(count,"зовнішній","зовнішні","зовнішніх");elements.importedSourceState.textContent=String(count);elements.importedSourceSummary.textContent=count?sources.join(", ")+" — "+ukCount(count,"запис","записи","записів"):"Ще не імпортовано";
  }
  async function importSourceFile(file){
    elements.importStatus.classList.remove("error");if(!file)return;if(file.size>2*1024*1024){elements.importStatus.textContent="Файл завеликий. Максимальний розмір — 2 МБ.";elements.importStatus.classList.add("error");return;}
    try{const text=await file.text();const extension=file.name.split(".").pop().toLowerCase();let rawRecords,backupNotes=null;if(extension==="json"){const parsed=JSON.parse(text);rawRecords=Array.isArray(parsed)?parsed:(Array.isArray(parsed.records)?parsed.records:(Array.isArray(parsed.externalRecords)?parsed.externalRecords:[]));if(parsed&&parsed.notes&&typeof parsed.notes==="object"&&!Array.isArray(parsed.notes))backupNotes=parsed.notes;}else rawRecords=parseCsv(text);const sourceName=file.name.replace(/\.[^.]+$/," ").trim()||"Імпорт";const records=rawRecords.map((raw,index)=>normalizeImportedRecord(raw,sourceName,index)).filter(Boolean);if(!records.length)throw new Error("format");state.externalRecords=records;if(backupNotes){state.notes=backupNotes;storeJson(STORAGE_KEYS.notes,state.notes);}if(!storeJson(STORAGE_KEYS.external,records))throw new Error("storage");updateSourceSummary();elements.importStatus.textContent="Імпортовано "+ukCount(records.length,"запис","записи","записів")+(backupNotes?" і відновлено примітки":"")+". Пошук у режимі «Порівняти» оновлено.";elements.sourceFile.value="";state.showAll=true;render();}catch(error){elements.importStatus.textContent="Не вдалося імпортувати файл. Перевірте формат і обов’язкові поля brand, model та lishi.";elements.importStatus.classList.add("error");}
  }
  function downloadJson(){
    const payload={exportedAt:new Date().toISOString(),externalRecords:state.externalRecords,notes:state.notes};const url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:"application/json"}));const link=document.createElement("a");link.href=url;link.download="lishi-finder-my-data.json";link.click();window.setTimeout(()=>URL.revokeObjectURL(url),1000);
  }
  function addOptions(select,items,label){uniqueSorted(items).forEach(value=>select.add(new Option(label?label(value):value,value)));}
  function plainMetadata(value){return new DOMParser().parseFromString(String(value||""),"text/html").body.textContent.replace(/\s+/g," ").trim();}
  function photoModelName(model){return String(model||"").split(/\s+\/\s+/)[0].replace(/\s+/g," ").trim();}
  function buildCommonsUrl(query){
    const params=new URLSearchParams({action:"query",generator:"search",gsrsearch:query,gsrnamespace:"6",gsrlimit:"3",prop:"imageinfo",iiprop:"url|mime|extmetadata",iiurlwidth:"1200",iiextmetadatalanguage:"uk",iiextmetadatafilter:"LicenseShortName|LicenseUrl|Artist|Credit|ImageDescription|ObjectName",format:"json",formatversion:"2",origin:"*"});
    return "https://commons.wikimedia.org/w/api.php?"+params.toString();
  }
  async function findCommonsPhoto(record,signal){
    const model=photoModelName(record.model);const simplified=model.replace(/\s*\([^)]*\)/g,"").trim();
    const queries=[record.brand+" "+model+" automobile",record.brand+" "+simplified].filter((value,index,array)=>value.trim()&&array.indexOf(value)===index);
    for(const query of queries){
      const response=await fetch(buildCommonsUrl(query),{signal,mode:"cors",credentials:"omit"});if(!response.ok)throw new Error("commons");const data=await response.json();
      const pages=(data.query&&Array.isArray(data.query.pages)?data.query.pages:[]).sort((left,right)=>(left.index||999)-(right.index||999));
      for(const page of pages){const info=page.imageinfo&&page.imageinfo[0];if(!info||!info.thumburl||!String(info.mime||"").startsWith("image/"))continue;const metadata=info.extmetadata||{};return{src:info.thumburl,source:info.descriptionurl||"https://commons.wikimedia.org/",title:plainMetadata(metadata.ObjectName&&metadata.ObjectName.value)||String(page.title||"").replace(/^File:/,""),artist:plainMetadata(metadata.Artist&&metadata.Artist.value),license:plainMetadata(metadata.LicenseShortName&&metadata.LicenseShortName.value)||"Wikimedia Commons"};}
    }return null;
  }
  function showPhotoMessage(message){elements.photoLoading.hidden=true;elements.photoImage.hidden=true;elements.photoCredit.hidden=true;elements.photoMessage.textContent=message;elements.photoMessage.hidden=false;}
  function resetPhotoDialog(record){
    elements.photoTitle.textContent=record.brand+" "+record.model;elements.photoLoading.hidden=false;elements.photoLoading.textContent="Шукаю відповідне фото…";elements.photoImage.hidden=true;elements.photoImage.removeAttribute("src");elements.photoImage.alt="";elements.photoMessage.hidden=true;elements.photoMessage.textContent="";elements.photoCredit.hidden=true;elements.photoCreditText.textContent="";elements.photoSource.href="https://commons.wikimedia.org/";
  }
  async function showPhoto(record){
    state.photoRequest+=1;const requestId=state.photoRequest;if(photoController)photoController.abort();photoController=new AbortController();resetPhotoDialog(record);
    if(!elements.photoDialog.open){if(typeof elements.photoDialog.showModal==="function")elements.photoDialog.showModal();else elements.photoDialog.setAttribute("open","");}
    if(!navigator.onLine){showPhotoMessage("Фото доступне лише за наявності інтернету.");return;}
    const cacheKey=record.brand+"|"+photoModelName(record.model);
    try{
      let photo=photoCache.get(cacheKey);if(!photoCache.has(cacheKey)){photo=await findCommonsPhoto(record,photoController.signal);photoCache.set(cacheKey,photo);}
      if(requestId!==state.photoRequest)return;if(!photo){showPhotoMessage("Не вдалося знайти надійне фото цієї моделі у Wikimedia Commons.");return;}
      await new Promise((resolve,reject)=>{elements.photoImage.onload=resolve;elements.photoImage.onerror=reject;elements.photoImage.src=photo.src;});if(requestId!==state.photoRequest)return;
      elements.photoImage.alt="Фото "+record.brand+" "+record.model;elements.photoImage.hidden=false;elements.photoLoading.hidden=true;elements.photoMessage.hidden=true;elements.photoCreditText.textContent=[photo.title,photo.artist&&"Автор: "+photo.artist,"Ліцензія: "+photo.license].filter(Boolean).join(" • ");elements.photoSource.href=photo.source;elements.photoCredit.hidden=false;
    }catch(error){if(error&&error.name==="AbortError")return;if(requestId===state.photoRequest)showPhotoMessage("Фото не завантажилося. Перевірте інтернет і спробуйте ще раз.");}
  }
  function closePhotoDialog(){state.photoRequest+=1;if(photoController)photoController.abort();elements.photoImage.removeAttribute("src");if(typeof elements.photoDialog.close==="function"&&elements.photoDialog.open)elements.photoDialog.close();else elements.photoDialog.removeAttribute("open");}
  function openSourcesDialog(){elements.importStatus.textContent="";elements.importStatus.classList.remove("error");if(typeof elements.sourcesDialog.showModal==="function")elements.sourcesDialog.showModal();else elements.sourcesDialog.setAttribute("open","");}
  function closeSourcesDialog(){if(typeof elements.sourcesDialog.close==="function"&&elements.sourcesDialog.open)elements.sourcesDialog.close();else elements.sourcesDialog.removeAttribute("open");}
  function makeBrandMark(brand){
    const mark=document.createElement("span");mark.className="brandMark";mark.setAttribute("aria-hidden","true");
    if(brandIcons[brand])mark.innerHTML=brandIcons[brand];else{mark.classList.add("brandMarkFallback");mark.textContent=brand?brand.charAt(0):"🚘";}return mark;
  }
  function closeBrandMenu({focusButton=false}={}){elements.brandMenu.hidden=true;elements.brandButton.setAttribute("aria-expanded","false");if(focusButton)elements.brandButton.focus();}
  function openBrandMenu(preferred="selected"){
    elements.brandMenu.hidden=false;elements.brandButton.setAttribute("aria-expanded","true");
    const options=[...elements.brandMenu.querySelectorAll(".brandOption")];const target=preferred==="last"?options.at(-1):(preferred==="first"?options[0]:options.find(option=>option.getAttribute("aria-selected")==="true")||options[0]);
    window.requestAnimationFrame(()=>target&&target.focus());
  }
  function selectBrand(brand,{showResults=true,focusButton=false}={}){
    elements.brand.value=brand;elements.brandButtonText.textContent=brand||"Усі марки";elements.brandButtonIcon.replaceWith(makeBrandMark(brand));elements.brandButtonIcon=elements.brandButton.querySelector(".brandMark");
    elements.brandMenu.querySelectorAll(".brandOption").forEach(option=>{const selected=option.dataset.brand===brand;option.classList.toggle("selected",selected);option.setAttribute("aria-selected",String(selected));});
    if(showResults)state.showAll=true;closeBrandMenu({focusButton});render();
  }
  function prepareBrandPicker(brands){
    ["",...brands].forEach(brand=>{const option=document.createElement("button");option.type="button";option.className="brandOption";option.setAttribute("role","option");option.dataset.brand=brand;option.setAttribute("aria-selected",String(!brand));option.append(makeBrandMark(brand),document.createTextNode(brand||"Усі марки"));option.addEventListener("click",()=>selectBrand(brand,{focusButton:true}));elements.brandMenu.append(option);});
    elements.brandButton.addEventListener("click",()=>elements.brandMenu.hidden?openBrandMenu():closeBrandMenu());
    elements.brandButton.addEventListener("keydown",event=>{if(event.key==="ArrowDown"||event.key==="ArrowUp"){event.preventDefault();openBrandMenu(event.key==="ArrowUp"?"last":"selected");}});
    elements.brandMenu.addEventListener("keydown",event=>{const options=[...elements.brandMenu.querySelectorAll(".brandOption")];const index=options.indexOf(document.activeElement);if(event.key==="Escape"){event.preventDefault();closeBrandMenu({focusButton:true});return;}if((event.key==="Enter"||event.key===" ")&&index>=0){event.preventDefault();options[index].click();return;}if(!["ArrowDown","ArrowUp","Home","End"].includes(event.key))return;event.preventDefault();let next=index;if(event.key==="Home")next=0;else if(event.key==="End")next=options.length-1;else next=(index+(event.key==="ArrowDown"?1:-1)+options.length)%options.length;options[next].focus();});
    document.addEventListener("pointerdown",event=>{if(!elements.brandPicker.contains(event.target))closeBrandMenu();});
  }
  function prepareFilters(){
    const brands=uniqueSorted(catalog.map(record=>record.brand));prepareBrandPicker(brands);
    addOptions(elements.market,catalog.flatMap(record=>record.markets||[]),value=>marketNames[value]||value);
    addOptions(elements.tool,catalog.filter(isVerified).map(record=>record.lishi));
    brands.forEach(brand=>{
      const button=document.createElement("button");button.type="button";button.className="brandChip";button.append(makeBrandMark(brand),document.createTextNode(brand));button.dataset.brand=brand;
      button.addEventListener("click",()=>selectBrand(elements.brand.value===brand?"":brand));elements.chips.append(button);
    });
  }
  function matchesQuery(record,query){
    if(!query)return true;
    const words=query.split(/\s+/).filter(Boolean);
    const searchable=state.mode==="lishi"?[record.lishi]:[record.brand,record.model,record.years,...(record.markets||[]),ignitionNames[record.ignition],state.mode==="compare"?record.lishi:""];
    return words.every(word=>searchable.some(value=>normalize(value).includes(word)));
  }
  function matchesYear(record,value){if(!value)return true;const year=Number(value);if(!Number.isInteger(year)||year<1900||year>2100)return false;if(!record.yearFrom)return false;return year>=record.yearFrom&&(!record.yearTo||year<=record.yearTo);}
  function activeCriteria(){return Boolean(elements.query.value.trim()||elements.brand.value||elements.market.value||elements.ignition.value||elements.year.value||elements.tool.value);}
  function filteredRecords(){
    const query=normalize(elements.query.value);
    return catalog.filter(record=>(!elements.brand.value||record.brand===elements.brand.value)&&(!elements.market.value||(record.markets||[]).includes(elements.market.value))&&(!elements.ignition.value||record.ignition===elements.ignition.value)&&(!elements.tool.value||record.lishi===elements.tool.value)&&matchesYear(record,elements.year.value)&&matchesQuery(record,query)).sort(sortRecords);
  }
  function externalFilteredRecords(){
    const query=normalize(elements.query.value);return state.externalRecords.filter(record=>(!elements.brand.value||normalize(record.brand)===normalize(elements.brand.value))&&(!elements.market.value||!(record.markets||[]).length||(record.markets||[]).some(value=>normalize(value)===normalize(elements.market.value)))&&(!elements.tool.value||record.lishi===elements.tool.value)&&matchesYear(record,elements.year.value)&&matchesQuery(record,query));
  }
  function comparisonRecords(){
    const internal=filteredRecords();const externalOnly=externalFilteredRecords().filter(external=>!catalog.some(record=>sameVehicle(record,external))).map(record=>({...record,_externalOnly:true}));return[...internal,...externalOnly].sort(sortRecords);
  }
  function appendComparisonRow(container,source,details,code,url){
    const row=document.createElement("div");row.className="comparisonRow";const sourceBlock=document.createElement("div");sourceBlock.className="comparisonSource";const heading=document.createElement(url?"a":"strong");heading.textContent=source;if(url){heading.href=url;heading.target="_blank";heading.rel="noopener noreferrer";}const meta=document.createElement("span");meta.textContent=details;sourceBlock.append(heading,meta);const value=document.createElement("div");value.className="comparisonCode";value.textContent=code||"—";row.append(sourceBlock,value);container.append(row);
  }
  function makeComparisonPanel(record){
    const panel=document.createElement("div");panel.className="cardPanel comparisonPanel";panel.hidden=true;const title=document.createElement("p");title.className="panelTitle";title.textContent="Порівняння джерел";panel.append(title);const matches=state.externalRecords.filter(external=>sameVehicle(record,external));const ownCode=record._externalOnly?"":record.lishi;const codes=matches.map(item=>normalize(item.lishi));const summary=document.createElement("div");
    if(record._externalOnly){summary.className="comparisonSummary pending";summary.textContent="Зовнішній запис відсутній у вашому каталозі LishiFinder.";}else if(record.alternativeLishi){summary.className="comparisonSummary conflict";summary.textContent="Основний код узято зі скріншота користувача; інший довідник збережено як примітку.";}else if(!matches.length){summary.className="comparisonSummary pending";summary.textContent="Зовнішні записи не імпортовані або відповідність не знайдена.";}else if(ownCode&&codes.every(code=>code===normalize(ownCode))){summary.className="comparisonSummary confirmed";summary.textContent="Збіг: усі імпортовані джерела вказують той самий Lishi.";}else{summary.className="comparisonSummary conflict";summary.textContent="Є розбіжність між вашим каталогом та зовнішніми джерелами.";}panel.append(summary);
    if(!record._externalOnly)appendComparisonRow(panel,record.source||"LishiFinder",[record.years,(record.markets||[]).map(value=>marketNames[value]||value).join(", "),record.checkedAt&&"Перевірено "+record.checkedAt].filter(Boolean).join(" • ")||"Вбудований запис",ownCode,safeSourceUrl(record.sourceUrl));
    if(!record._externalOnly&&record.alternativeLishi)appendComparisonRow(panel,record.alternativeSource||"Альтернативне джерело",record.alternativeNote||"Альтернативний код",record.alternativeLishi,safeSourceUrl(record.alternativeSourceUrl));
    matches.forEach(item=>appendComparisonRow(panel,item.source||"Імпорт",[item.years,item.note].filter(Boolean).join(" • ")||"Імпортований запис",item.lishi,safeSourceUrl(item.sourceUrl)));
    const links=document.createElement("div");links.className="comparisonLinks";sourceLinks.forEach(source=>{const link=document.createElement("a");link.href=source.url;link.target="_blank";link.rel="noopener noreferrer";link.textContent="Перевірити "+source.name+" ↗";links.append(link);});panel.append(links);return panel;
  }
  function makeNotePanel(record,button){
    const key=recordKey(record);const panel=document.createElement("div");panel.className="cardPanel noteEditor";panel.hidden=true;const label=document.createElement("label");const textarea=document.createElement("textarea");textarea.id="note-"+Math.random().toString(36).slice(2);label.htmlFor=textarea.id;label.textContent="Моя примітка для "+record.brand+" "+record.model;textarea.value=state.notes[key]||"";textarea.placeholder="Наприклад: перевірено на автомобілі клієнта, відрізняється ринок або потрібен інший інструмент…";textarea.maxLength=2000;const actions=document.createElement("div");actions.className="noteActions";const save=document.createElement("button");save.type="button";save.className="noteButton";save.textContent="Зберегти";const remove=document.createElement("button");remove.type="button";remove.className="noteButton delete";remove.textContent="Видалити";const status=document.createElement("span");status.className="noteStatus";
    save.addEventListener("click",()=>{const value=textarea.value.trim();if(value)state.notes[key]=value;else delete state.notes[key];if(storeJson(STORAGE_KEYS.notes,state.notes)){button.classList.toggle("hasNote",Boolean(value));button.textContent=value?"📝 Є примітка":"📝 Моя примітка";status.textContent=value?"Збережено на цьому пристрої":"Порожню примітку видалено";}else status.textContent="Не вдалося зберегти";});
    remove.addEventListener("click",()=>{textarea.value="";delete state.notes[key];storeJson(STORAGE_KEYS.notes,state.notes);button.classList.remove("hasNote");button.textContent="📝 Моя примітка";status.textContent="Видалено";});actions.append(save,remove,status);panel.append(label,textarea,actions);return panel;
  }
  function profileInfo(record){const code=String(record.lishi||"").trim().toUpperCase();const entry=profileCatalog[code]||null;const sourceKey=entry&&entry.source;const source=profileSources[sourceKey]||null;let verification="unknown";if(entry&&entry.shape!=="unknown"){if(sourceKey==="user")verification="user";else if(String(sourceKey||"").startsWith("official"))verification="official";else verification="reference";}return{code,entry,source,verification,sourceUrl:safeSourceUrl((entry&&entry.url)||(source&&source.url)),sourceLabel:(source&&source.label)||"Джерело не вказано"};}
  function inferredKeyShape(record){const explicit=String(record.keyShape||"").toLowerCase();if(keyShapeNames[explicit])return explicit;const info=profileInfo(record);if(info.entry&&keyShapeNames[info.entry.shape])return info.entry.shape;if(!info.code&&(record.ignition==="prox"||record.ignition==="smart"))return"fob";return"unknown";}
  function makeKeyShape(record){const ns="http://www.w3.org/2000/svg",shape=inferredKeyShape(record),svg=document.createElementNS(ns,"svg");svg.setAttribute("viewBox","0 0 280 120");svg.setAttribute("role","img");svg.setAttribute("aria-label","Схематична форма ключа: "+keyShapeNames[shape]);svg.classList.add("keyShapeSvg");const add=(name,attributes)=>{const node=document.createElementNS(ns,name);Object.entries(attributes).forEach(([key,value])=>node.setAttribute(key,value));svg.append(node);return node;};if(shape==="fob"){add("rect",{x:"48",y:"16",width:"82",height:"88",rx:"30",class:"keyHandle"});add("circle",{cx:"89",cy:"43",r:"8",class:"keyButton"});add("rect",{x:"78",y:"60",width:"22",height:"8",rx:"4",class:"keyButton"});add("path",{d:"M130 48H247V72H130Z",class:"keyBlade"});add("path",{d:"M176 48v10h18V48m17 24V62h18v10",class:"keyCut"});}else if(shape==="tibbe"){add("rect",{x:"30",y:"22",width:"86",height:"76",rx:"24",class:"keyHandle"});add("circle",{cx:"62",cy:"60",r:"12",class:"keyHole"});add("path",{d:"M112 49H244V71H112Z",class:"keyBlade"});add("path",{d:"M126 49l10 22 10-22 10 22 10-22 10 22 10-22 10 22 10-22",class:"keyGroove"});add("circle",{cx:"232",cy:"60",r:"5",class:"keyCut"});}else if(shape==="edge"){add("circle",{cx:"70",cy:"60",r:"40",class:"keyHandle"});add("circle",{cx:"70",cy:"60",r:"13",class:"keyHole"});add("path",{d:"M108 47H248V68h-17l-8 11-15-11-10 11-15-11h-75Z",class:"keyBlade"});add("path",{d:"M137 54h72",class:"keyGroove"});}else if(shape==="laser"){add("rect",{x:"30",y:"24",width:"88",height:"72",rx:"25",class:"keyHandle"});add("circle",{cx:"62",cy:"60",r:"12",class:"keyHole"});add("rect",{x:"112",y:"43",width:"136",height:"34",rx:"5",class:"keyBlade"});add("path",{d:"M134 60h23l10-9h26l10 18h24",class:"keyGroove"});}else{add("rect",{x:"35",y:"25",width:"78",height:"70",rx:"24",class:"keyHandle"});add("rect",{x:"108",y:"45",width:"140",height:"30",rx:"5",class:"keyBlade"});add("text",{x:"178",y:"66",class:"keyUnknown"}).textContent="?";}return svg;}
  function appendReferenceLink(container,url,label){const safeUrl=safeSourceUrl(url);if(!safeUrl)return;const link=document.createElement("a");link.href=safeUrl;link.target="_blank";link.rel="noopener noreferrer";link.textContent=label+" ↗";container.append(link);}
  function makeKeyPanel(record){const info=profileInfo(record),panel=document.createElement("div");panel.className="cardPanel keyPanel";panel.hidden=true;const title=document.createElement("p");title.className="panelTitle";title.textContent="Ключ і форма замка";const layout=document.createElement("div");layout.className="keyLayout";const shape=document.createElement("div");shape.className="keyShapeCard";shape.append(makeKeyShape(record));const shapeText=document.createElement("strong");shapeText.textContent=keyShapeNames[inferredKeyShape(record)];const shapeHint=document.createElement("span");shapeHint.textContent="Схематичний контур • профіль "+(record.keyShapeLabel||record.lishi||"не підтверджено");shape.append(shapeText,shapeHint);const details=document.createElement("dl");details.className="keyDetails";[["Профіль замка / Lishi",record.lishi||"Потрібна перевірка"],["Тип запуску",ignitionNames[record.ignition]||ignitionNames.unknown],["Чип",record.chip||"Не вказано"],["Перевірка форми",verificationNames[info.verification]]].forEach(([label,value])=>{const dt=document.createElement("dt"),dd=document.createElement("dd");dt.textContent=label;dd.textContent=value;details.append(dt,dd);});layout.append(shape,details);panel.append(title,layout);if(info.entry&&info.entry.note){const warning=document.createElement("p");warning.className="profileWarning";warning.textContent=info.entry.note;panel.append(warning);}const references=document.createElement("div");references.className="keyReferences";appendReferenceLink(references,info.sourceUrl,info.sourceLabel);if(keyPhotoReference)appendReferenceLink(references,keyPhotoReference.url,keyPhotoReference.label);if(references.childElementCount)panel.append(references);const photoUrl=safeImageUrl(record.keyPhoto),photoBlock=document.createElement("div");photoBlock.className="keyPhotoBlock";if(photoUrl){const image=document.createElement("img");image.src=photoUrl;image.alt=record.keyPhotoAlt||("Фото ключа для "+record.brand+" "+record.model);image.loading="lazy";image.decoding="async";photoBlock.append(image);const sourceUrl=safeSourceUrl(record.keyPhotoSource);if(sourceUrl)appendReferenceLink(photoBlock,sourceUrl,"Джерело фото ключа");}else{const missing=document.createElement("p");missing.className="keyPhotoMissing";missing.textContent="Перевіреного фото саме цього ключа ще немає. Скріншоти використано для звірки форми, але сторонні зображення не копіюються без дозволу; нижче доступний офіційний каталог фото-зразків.";photoBlock.append(missing);}panel.append(photoBlock);return panel;}
  function togglePanel(button,panel,others=[]){const opening=panel.hidden;others.forEach(([otherButton,otherPanel])=>{otherPanel.hidden=true;otherButton.classList.remove("active");otherButton.setAttribute("aria-expanded","false");});panel.hidden=!opening;button.classList.toggle("active",opening);button.setAttribute("aria-expanded",String(opening));if(opening){const input=panel.querySelector("textarea");if(input)input.focus();}}
  function makeCard(record){
    const card=document.createElement("article");card.className="card";const top=document.createElement("div");top.className="cardTop";const info=document.createElement("div");info.className="info";
    const brand=document.createElement("div");brand.className="brand brandWithMark";brand.append(makeBrandMark(record.brand),document.createTextNode(record.brand));const model=document.createElement("button");model.type="button";model.className="model modelPhotoButton";model.title="Показати фото";model.setAttribute("aria-label","Показати фото "+record.brand+" "+record.model);model.append(document.createTextNode(record.model),Object.assign(document.createElement("span"),{className:"modelPhotoIcon",textContent:"📷"}));model.addEventListener("click",()=>showPhoto(record));
    const meta=document.createElement("div");meta.className="meta";const marketLabel=(record.markets||[]).map(value=>marketNames[value]||value).join(", ");meta.textContent=(record.years||"Рік не вказано")+" • "+(marketLabel||"Ринок не вказано")+" • "+(ignitionNames[record.ignition]||ignitionNames.unknown)+(record.chip?" • Чип: "+record.chip:"");
    info.append(brand,model,meta);const badge=document.createElement("div");badge.className="badge"+(isVerified(record)?"":" warning");badge.textContent=isVerified(record)?record.lishi:(record.status==="not_available"?"Немає даних":"Потрібна перевірка");top.append(info,badge);card.append(top);
    if(record._externalOnly){const externalLabel=document.createElement("p");externalLabel.className="recordNote";externalLabel.textContent="Лише зовнішнє джерело: "+(record.source||"Імпорт");card.append(externalLabel);}else if(record.note){const note=document.createElement("p");note.className="recordNote";note.textContent=record.note;card.append(note);}
    const actions=document.createElement("div");actions.className="cardActions";const keyButton=document.createElement("button");keyButton.type="button";keyButton.className="cardAction";keyButton.textContent="🔑 Ключ / замок";keyButton.setAttribute("aria-expanded","false");const compareButton=document.createElement("button");compareButton.type="button";compareButton.className="cardAction";compareButton.textContent="📚 Порівняти джерела";compareButton.setAttribute("aria-expanded","false");const noteButton=document.createElement("button");noteButton.type="button";noteButton.className="cardAction"+(state.notes[recordKey(record)]?" hasNote":"");noteButton.textContent=state.notes[recordKey(record)]?"📝 Є примітка":"📝 Моя примітка";noteButton.setAttribute("aria-expanded","false");const keyPanel=makeKeyPanel(record),comparisonPanel=makeComparisonPanel(record),notePanel=makeNotePanel(record,noteButton);keyButton.addEventListener("click",()=>togglePanel(keyButton,keyPanel,[[compareButton,comparisonPanel],[noteButton,notePanel]]));compareButton.addEventListener("click",()=>togglePanel(compareButton,comparisonPanel,[[keyButton,keyPanel],[noteButton,notePanel]]));noteButton.addEventListener("click",()=>togglePanel(noteButton,notePanel,[[keyButton,keyPanel],[compareButton,comparisonPanel]]));actions.append(keyButton,compareButton,noteButton);card.append(actions,keyPanel,comparisonPanel,notePanel);if(state.mode==="compare"){comparisonPanel.hidden=false;compareButton.classList.add("active");compareButton.setAttribute("aria-expanded","true");}return card;
  }
  function renderMode(){
    const auto=state.mode==="auto",compare=state.mode==="compare";elements.query.placeholder=auto?"Toyota RAV4, Volkswagen Golf…":(compare?"Авто або код Lishi для порівняння…":"HU66, TOY43AT, HU127T…");
    elements.modeHelp.textContent=auto?"Введіть марку, модель, ринок або рік — каталог покаже відповідний код Lishi.":(compare?"Порівняйте ваш каталог з імпортованими дозволеними джерелами та власними примітками.":"Введіть код Lishi — каталог покаже автомобілі, для яких він зазначений.");
    document.querySelectorAll(".mode").forEach(button=>{const selected=button.dataset.mode===state.mode;button.classList.toggle("active",selected);button.setAttribute("aria-pressed",String(selected));});
  }
  function render(){
    renderMode();elements.chips.querySelectorAll(".brandChip").forEach(button=>button.classList.toggle("selected",button.dataset.brand===elements.brand.value));
    const criteria=activeCriteria();const records=state.mode==="compare"?comparisonRecords():filteredRecords();elements.results.replaceChildren();elements.showAll.hidden=criteria||state.showAll;
    if(!criteria&&!state.showAll){elements.stats.textContent="У каталозі "+catalog.length+" записів. Оберіть марку, скористайтеся пошуком або відкрийте весь каталог.";const empty=document.createElement("div");empty.className="empty";empty.textContent="Щоб зменшити навантаження на телефон, повний каталог не показується одразу.";elements.results.append(empty);return;}
    elements.stats.textContent="Знайдено: "+records.length;
    if(!records.length){const empty=document.createElement("div");empty.className="empty";empty.textContent=state.mode==="lishi"?"Код не знайдено серед перевірених записів.":(state.mode==="compare"?"Збігів немає. Імпортуйте дозволений CSV/JSON або змініть запит.":"Нічого не знайдено. Перевірте марку, ринок, рік або тип ключа.");elements.results.append(empty);return;}
    const fragment=document.createDocumentFragment();records.forEach(record=>fragment.append(makeCard(record)));elements.results.append(fragment);
  }
  async function refreshOfflineVersion(){
    elements.reset.disabled=true;elements.updateStatus.textContent="Очищення кешу цього застосунку…";
    try{
      if("caches" in window){const keys=await caches.keys();await Promise.all(keys.filter(key=>key.startsWith("lishi-finder-")).map(key=>caches.delete(key)));}
      if("serviceWorker" in navigator){const registration=await navigator.serviceWorker.getRegistration();const appPath=new URL("./",location.href).pathname;if(registration&&new URL(registration.scope).pathname.startsWith(appPath))await registration.unregister();}
      elements.updateStatus.textContent="Офлайн-версію очищено. Завантажую актуальні дані…";window.setTimeout(()=>location.reload(),350);
    }catch(error){elements.reset.disabled=false;elements.updateStatus.textContent="Не вдалося оновити кеш. Спробуйте ще раз, коли буде інтернет.";}
  }
  function registerServiceWorker(){
    if(!("serviceWorker" in navigator))return;
    window.addEventListener("load",()=>{navigator.serviceWorker.register("./sw.js",{updateViaCache:"none"}).then(registration=>{const hadActiveWorker=Boolean(registration.active);registration.update().catch(()=>{});registration.addEventListener("updatefound",()=>{if(hadActiveWorker)elements.updateStatus.textContent="Доступна нова офлайн-версія. Натисніть «Оновити офлайн-версію».";});if(!hadActiveWorker)elements.updateStatus.textContent="Офлайн-версію встановлено для наступного запуску.";}).catch(()=>{elements.updateStatus.textContent="Офлайн-режим недоступний у цьому переглядачі.";});});
  }
  document.querySelectorAll(".mode").forEach(button=>button.addEventListener("click",()=>{state.mode=button.dataset.mode;state.showAll=false;elements.query.value="";render();}));
  elements.query.addEventListener("input",()=>{state.showAll=true;render();});elements.year.addEventListener("input",()=>{state.showAll=true;render();});
  [elements.market,elements.ignition,elements.tool].forEach(element=>element.addEventListener("change",()=>{state.showAll=true;render();}));
  elements.clear.addEventListener("click",()=>{elements.query.value="";elements.query.focus();state.showAll=false;render();});elements.showAll.addEventListener("click",()=>{state.showAll=true;render();});elements.reset.addEventListener("click",refreshOfflineVersion);
  elements.photoClose.addEventListener("click",closePhotoDialog);elements.photoDialog.addEventListener("click",event=>{if(event.target===elements.photoDialog)closePhotoDialog();});elements.photoDialog.addEventListener("close",()=>{state.photoRequest+=1;if(photoController)photoController.abort();elements.photoImage.removeAttribute("src");});
  elements.manageSources.addEventListener("click",openSourcesDialog);elements.sourcesClose.addEventListener("click",closeSourcesDialog);elements.sourcesDialog.addEventListener("click",event=>{if(event.target===elements.sourcesDialog)closeSourcesDialog();});elements.sourceFile.addEventListener("change",()=>importSourceFile(elements.sourceFile.files&&elements.sourceFile.files[0]));elements.clearSources.addEventListener("click",()=>{if(!state.externalRecords.length){elements.importStatus.textContent="Імпортованих записів немає.";return;}if(!window.confirm("Видалити всі імпортовані зовнішні записи з цього пристрою?"))return;state.externalRecords=[];storeJson(STORAGE_KEYS.external,[]);updateSourceSummary();elements.importStatus.textContent="Імпортовані записи видалено. Ваші примітки збережено.";render();});elements.exportData.addEventListener("click",downloadJson);
  const storedExternal=readStoredJson(STORAGE_KEYS.external,[]),storedNotes=readStoredJson(STORAGE_KEYS.notes,{});state.externalRecords=Array.isArray(storedExternal)?storedExternal:[];state.notes=storedNotes&&typeof storedNotes==="object"&&!Array.isArray(storedNotes)?storedNotes:{};elements.builtinCatalogSummary.textContent="Вбудований каталог — "+ukCount(catalog.length,"запис","записи","записів");elements.catalogPill.textContent=ukCount(uniqueSorted(catalog.map(record=>record.brand)).length,"марка","марки","марок")+" • "+ukCount(catalog.length,"запис","записи","записів");updateSourceSummary();prepareFilters();render();registerServiceWorker();
})();
