window.LISHI_PROFILES = {
  "version": "2026-08-17.1",
  "updatedAt": "2026-08-17",
  "sources": {
    "user": {
      "label": "Скріншоти користувача",
      "priority": 1
    },
    "official-silca": {
      "label": "Silca — офіційний каталог",
      "url": "https://www.silca.biz/en/global/products/delta-2000-fo",
      "priority": 2
    },
    "official-lishi": {
      "label": "Original Lishi — офіційний каталог",
      "url": "https://www.originallishi.com/lishi-tools-full-list/",
      "priority": 2
    },
    "reference": {
      "label": "Довідникова класифікація — потрібна звірка",
      "url": "https://www.originallishi.com/lishi-tools-full-list/",
      "priority": 3
    }
  },
  "keyPhotoReference": {
    "label": "Офіційний каталог корпусів і фото ключів Ilco",
    "url": "https://www.ilco.us/company/empty-shells-vehicle-applications"
  },
  "profiles": {
    "CY24": {"shape": "edge", "source": "user"},
    "FO21P": {"shape": "tibbe", "source": "official-silca"},
    "FO34": {"shape": "edge", "source": "user"},
    "FO38R": {"shape": "edge", "source": "user"},
    "FO42R": {"shape": "edge", "source": "user"},
    "GT15R": {"shape": "edge", "source": "user"},
    "GT21": {"shape": "unknown", "source": "user", "note": "На скріншоті підтверджено брелок, але не форму аварійного леза."},
    "HON58R": {"shape": "edge", "source": "user"},
    "HON66": {"shape": "laser", "source": "user", "url": "https://www.originallishi.com/2-in-1tools/hon66-2-in-1/"},
    "HU100": {"shape": "laser", "source": "reference"},
    "HU101": {"shape": "laser", "source": "user", "url": "https://www.originallishi.com/hu101-v3-cutout-2-in-1-pick/"},
    "HU127T": {"shape": "laser", "source": "reference"},
    "HU134": {"shape": "laser", "source": "user"},
    "HU136": {"shape": "laser", "source": "reference"},
    "HU162T-10": {"shape": "laser", "source": "reference"},
    "HU162T-8": {"shape": "laser", "source": "reference"},
    "HU162T-9": {"shape": "laser", "source": "reference"},
    "HU198T": {"shape": "laser", "source": "user"},
    "HU39": {"shape": "laser", "source": "reference"},
    "HU43": {"shape": "edge", "source": "reference"},
    "HU49": {"shape": "edge", "source": "reference"},
    "HU58": {"shape": "laser", "source": "reference"},
    "HU64": {"shape": "laser", "source": "reference"},
    "HU66": {"shape": "laser", "source": "official-lishi"},
    "HU83": {"shape": "laser", "source": "user"},
    "HU92R": {"shape": "laser", "source": "reference"},
    "HY22": {"shape": "edge", "source": "reference"},
    "HYN10": {"shape": "edge", "source": "user"},
    "HYN11": {"shape": "edge", "source": "reference"},
    "HYN14": {"shape": "edge", "source": "user"},
    "HYN14R": {"shape": "edge", "source": "user"},
    "HYN15": {"shape": "edge", "source": "user"},
    "HYN17": {"shape": "laser", "source": "user"},
    "HYN17R": {"shape": "laser", "source": "user"},
    "HYN6": {"shape": "edge", "source": "user"},
    "HYN7R": {"shape": "edge", "source": "user"},
    "KIA10": {"shape": "laser", "source": "user"},
    "KIA3R": {"shape": "edge", "source": "user"},
    "KIA7": {"shape": "laser", "source": "user"},
    "KIA9(7)": {"shape": "laser", "source": "user"},
    "KIA9(8)": {"shape": "laser", "source": "user"},
    "KK12": {"shape": "laser", "source": "user"},
    "MAZ13": {"shape": "edge", "source": "user"},
    "MAZ24R": {"shape": "edge", "source": "user"},
    "NE72": {"shape": "edge", "source": "reference"},
    "NE73": {"shape": "edge", "source": "reference"},
    "NSN14": {"shape": "edge", "source": "reference"},
    "SIP16": {"shape": "edge", "source": "user"},
    "SIP22": {"shape": "laser", "source": "user"},
    "SX9AP": {"shape": "edge", "source": "reference"},
    "TOY30": {"shape": "edge", "source": "reference"},
    "TOY38R": {"shape": "edge", "source": "reference"},
    "TOY40": {"shape": "edge", "source": "reference"},
    "TOY43": {"shape": "edge", "source": "reference"},
    "TOY43AT": {"shape": "edge", "source": "reference"},
    "TOY47": {"shape": "laser", "source": "reference"},
    "TOY48": {"shape": "laser", "source": "reference"},
    "TOY48-E": {"shape": "laser", "source": "reference"},
    "TOY49": {"shape": "laser", "source": "user"},
    "TOY51": {"shape": "unknown", "source": "reference", "note": "Код є у каталозі, але форма профілю ще не підтверджена пріоритетним джерелом."},
    "VA2": {"shape": "laser", "source": "user"},
    "VA2T": {"shape": "laser", "source": "reference"},
    "VA6": {"shape": "laser", "source": "reference"},
    "VAT2": {"shape": "laser", "source": "reference"},
    "YM15": {"shape": "edge", "source": "reference"}
  }
};
